# Generated by Django 2.1.5 on 2019-01-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('youtube_link', models.CharField(max_length=200)),
            ],
        ),
    ]
